@host = http://127.0.0.1:5000/bookshelf

POST  {{host}}/features
Content-Type: application/json

{
  "user_id": 10000,
  "genres": [
    "drama",
    "humor",
    "fiction"
  ],
  "authors": [
    "Arthur Conan Doyle"
  ],
  "time_periods": [
    0,
    1
  ] 
}
