@host = http://127.0.0.1:5000/bookshelf


POST  {{host}}/login
Content-Type: application/json

{
  "email": "doe@mail.com"
}

###

POST  {{host}}/login
Content-Type: application/json

{
  "email": "lucy@mail.com"
}
