@host = http://127.0.0.1:5000/bookshelf

POST  {{host}}/rating
Content-Type: application/json

{
  "user_id": "300",
  "book_id": "2",
  "rating": 4,
  "read_ratio": 0.7,
  "shared": 8,
  "comment": "Impresive!"
}
