from entities_repr import Book, User

principito = Book( 1 ,"El Principito", "Antoine de Saint-Exupéry", 1943, "Spanish", ["Fiction", "Children"])
alquimista = Book( 2,"El Alquimista", "Paulo Coelho", 1988, "Spanish", ["Fiction"])
angel_demonio = Book(3, "Ángeles y Demonios", "Dan Brown", 2000, "Spanish", ["Fiction", "Mystery"])
probability_essentials = Book(4, "Probability Essentials", "Jean Jacod", 2003, "English", ["Mathematics"])

harry_potter = Book(5,"Harry Potter and the Philosopher's Stone", "J.K. Rowling", 1997, "English", ["Fiction", "Fantasy"])
to_kill_a_mockingbird = Book(6,"To Kill a Mockingbird", "Harper Lee", 1960, "English", ["Fiction", "Classic"])
lord_rings = Book(7,"The Lord of the Rings", "J.R.R. Tolkien", 1954, "English", ["Fiction", "Fantasy"])
hunger_games = Book(8,"The Hunger Games", "Suzanne Collins", 2008, "English", ["Fiction", "Dystopian"])
catcher = Book(9, "The Catcher in the Rye", "J.D. Salinger", 1951, "English", ["Fiction", "Classic"])
gatsby = Book(10,"The Great Gatsby", "F. Scott Fitzgerald", 1925, "English", ["Fiction", "Classic"])
flies = Book(0, "Lord of the Flies", "William Golding", 1954, "English", ["Fiction", "Classic"])
catch = Book(11, "Catch-22", "Joseph Heller", 1961, "English", ["Fiction", "Classic"])
grapes = Book(12, "The Grapes of Wrath", "John Steinbeck", 1939, "English", ["Fiction", "Classic"])
gone = Book(13, "Gone with the Wind", "Margaret Mitchell", 1936, "English", ["Fiction", "Classic"])
lolita = Book(14, "Lolita", "Vladimir Nabokov", 1955, "English", ["Fiction", "Classic"])
slaughterhouse = Book(15, "Slaughterhouse-Five", "Kurt Vonnegut", 1969, "English", ["Fiction", "Classic"])
watchmen = Book(16, "Watchmen", "Alan Moore", 1987, "English", ["Fiction", "Graphic Novel"])
atonement = Book(17, "Atonement", "Ian McEwan", 2001, "English", ["Fiction"])
possession = Book(18, "Possession", "A.S. Byatt", 1990, "English", ["Fiction"])
sun = Book(19, "The Sun Also Rises", "Ernest Hemingway", 1926, "English", ["Fiction", "Classic"])
ragtime = Book(20, "Ragtime", "E.L. Doctorow", 1975, "English", ["Fiction"])
naked_lunch = Book(21, "Naked Lunch", "William S. Burroughs", 1959, "English", ["Fiction"])
gravity_rainbow = Book(22, "Gravity's Rainbow", "Thomas Pynchon", 1973, "English", ["Fiction"])
white_noise = Book(23, "White Noise", "Don DeLillo", 1985, "English", ["Fiction"])
beloved = Book(24, "Beloved", "Toni Morrison", 1987, "English", ["Fiction"])
midnight_children = Book(25, "Midnight's Children", "Salman Rushdie", 1981, "English", ["Fiction"])
house_leaves = Book(26,"House of Leaves", "Mark Z. Danielewski", 2000, "English", ["Fiction"])
corrections = Book(27,"The Corrections", "Jonathan Franzen", 2001, "English", ["Fiction"])
brief_wondrous = Book(28,"The Brief Wondrous Life of Oscar Wao", "Junot Díaz", 2007, "English", ["Fiction"])
cloud_atlas = Book(29,"Cloud Atlas", "David Mitchell", 2004, "English", ["Fiction"])
fortress = Book(30, "The Fortress of Solitude", "Jonathan Lethem", 2003, "English", ["Fiction"])
kavalier_clay = Book(31,"The Amazing Adventures of Kavalier & Clay", "Michael Chabon", 2000, "English", ["Fiction"])
sympathizer = Book(32,"The Sympathizer", "Viet Thanh Nguyen", 2015, "English", ["Fiction"])
underground_railroad = Book(33,"The Underground Railroad", "Colson Whitehead", 2016, "English", ["Fiction"])
lincoln_bardo = Book(34, "Lincoln in the Bardo", "George Saunders", 2017, "English", ["Fiction"])
overstory = Book(35, "The Overstory", "Richard Powers", 2018, "English", ["Fiction"])

introduction_linear_algebra = Book(36,"Introduction to Linear Algebra", "Gilbert Strang", 1993, "English", ["Mathematics"])
calculus = Book(37, "Calculus", "Michael Spivak", 1967, "English", ["Mathematics"])
abstract_algebra = Book(38, "Abstract Algebra", "David S. Dummit", 1999, "English", ["Mathematics"])
real_analysis = Book(39,"Principles of Mathematical Analysis", "Walter Rudin", 1953, "English", ["Mathematics"])
complex_analysis = Book(40,"Complex Analysis", "Lars Ahlfors", 1953, "English", ["Mathematics"])
topology = Book(41, "Topology", "James R. Munkres", 1974, "English", ["Mathematics"])
number_theory = Book(42, "An Introduction to the Theory of Numbers", "G.H. Hardy", 1938, "English", ["Mathematics"])
discrete_mathematics = Book(43, "Discrete Mathematics and Its Applications", "Kenneth H. Rosen", 1988, "English", ["Mathematics"])
probability_theory = Book(44, "Probability Theory: The Logic of Science", "E.T. Jaynes", 2003, "English", ["Mathematics"])
statistical_learning = Book(45, "The Elements of Statistical Learning", "Trevor Hastie", 2001, "English", ["Mathematics"])

books = [
    principito, alquimista, angel_demonio, probability_essentials, harry_potter, to_kill_a_mockingbird, lord_rings, hunger_games, catcher, gatsby, flies, catch, grapes, gone, lolita, slaughterhouse, watchmen, atonement, possession, sun, ragtime, naked_lunch, gravity_rainbow,
    white_noise, beloved, midnight_children, house_leaves, corrections, brief_wondrous, cloud_atlas, fortress, kavalier_clay, sympathizer, underground_railroad, lincoln_bardo, overstory,
    introduction_linear_algebra, calculus, abstract_algebra, real_analysis, complex_analysis, topology, number_theory, discrete_mathematics, probability_theory, statistical_learning
]