from entities_repr import Book, User

principito = Book("El Principito", "Antoine de Saint-Exupéry", 1943, "Spanish", ["Fiction", "Children"])
alquimista = Book("El Alquimista", "Paulo Coelho", 1988, "Spanish", ["Fiction"])
angel_demonio = Book("Ángeles y Demonios", "Dan Brown", 2000, "Spanish", ["Fiction", "Mystery"])
probability_essentials = Book("Probability Essentials", "Jean Jacod", 2003, "English", ["Mathematics"])

harry_potter = Book("Harry Potter and the Philosopher's Stone", "J.K. Rowling", 1997, "English", ["Fiction", "Fantasy"])
to_kill_a_mockingbird = Book("To Kill a Mockingbird", "Harper Lee", 1960, "English", ["Fiction", "Classic"])
lord_rings = Book("The Lord of the Rings", "J.R.R. Tolkien", 1954, "English", ["Fiction", "Fantasy"])
hunger_games = Book("The Hunger Games", "Suzanne Collins", 2008, "English", ["Fiction", "Dystopian"])
catcher = Book("The Catcher in the Rye", "J.D. Salinger", 1951, "English", ["Fiction", "Classic"])
gatsby = Book("The Great Gatsby", "F. Scott Fitzgerald", 1925, "English", ["Fiction", "Classic"])
flies = Book("Lord of the Flies", "William Golding", 1954, "English", ["Fiction", "Classic"])
catch = Book("Catch-22", "Joseph Heller", 1961, "English", ["Fiction", "Classic"])
grapes = Book("The Grapes of Wrath", "John Steinbeck", 1939, "English", ["Fiction", "Classic"])
gone = Book("Gone with the Wind", "Margaret Mitchell", 1936, "English", ["Fiction", "Classic"])
lolita = Book("Lolita", "Vladimir Nabokov", 1955, "English", ["Fiction", "Classic"])
slaughterhouse = Book("Slaughterhouse-Five", "Kurt Vonnegut", 1969, "English", ["Fiction", "Classic"])
watchmen = Book("Watchmen", "Alan Moore", 1987, "English", ["Fiction", "Graphic Novel"])
atonement = Book("Atonement", "Ian McEwan", 2001, "English", ["Fiction"])
possession = Book("Possession", "A.S. Byatt", 1990, "English", ["Fiction"])
sun = Book("The Sun Also Rises", "Ernest Hemingway", 1926, "English", ["Fiction", "Classic"])
ragtime = Book("Ragtime", "E.L. Doctorow", 1975, "English", ["Fiction"])
naked_lunch = Book("Naked Lunch", "William S. Burroughs", 1959, "English", ["Fiction"])
gravity_rainbow = Book("Gravity's Rainbow", "Thomas Pynchon", 1973, "English", ["Fiction"])
white_noise = Book("White Noise", "Don DeLillo", 1985, "English", ["Fiction"])
beloved = Book("Beloved", "Toni Morrison", 1987, "English", ["Fiction"])
midnight_children = Book("Midnight's Children", "Salman Rushdie", 1981, "English", ["Fiction"])
house_leaves = Book("House of Leaves", "Mark Z. Danielewski", 2000, "English", ["Fiction"])
corrections = Book("The Corrections", "Jonathan Franzen", 2001, "English", ["Fiction"])
brief_wondrous = Book("The Brief Wondrous Life of Oscar Wao", "Junot Díaz", 2007, "English", ["Fiction"])
cloud_atlas = Book("Cloud Atlas", "David Mitchell", 2004, "English", ["Fiction"])
fortress = Book("The Fortress of Solitude", "Jonathan Lethem", 2003, "English", ["Fiction"])
kavalier_clay = Book("The Amazing Adventures of Kavalier & Clay", "Michael Chabon", 2000, "English", ["Fiction"])
sympathizer = Book("The Sympathizer", "Viet Thanh Nguyen", 2015, "English", ["Fiction"])
underground_railroad = Book("The Underground Railroad", "Colson Whitehead", 2016, "English", ["Fiction"])
lincoln_bardo = Book("Lincoln in the Bardo", "George Saunders", 2017, "English", ["Fiction"])
overstory = Book("The Overstory", "Richard Powers", 2018, "English", ["Fiction"])

introduction_linear_algebra = Book("Introduction to Linear Algebra", "Gilbert Strang", 1993, "English", ["Mathematics"])
calculus = Book("Calculus", "Michael Spivak", 1967, "English", ["Mathematics"])
abstract_algebra = Book("Abstract Algebra", "David S. Dummit", 1999, "English", ["Mathematics"])
real_analysis = Book("Principles of Mathematical Analysis", "Walter Rudin", 1953, "English", ["Mathematics"])
complex_analysis = Book("Complex Analysis", "Lars Ahlfors", 1953, "English", ["Mathematics"])
topology = Book("Topology", "James R. Munkres", 1974, "English", ["Mathematics"])
number_theory = Book("An Introduction to the Theory of Numbers", "G.H. Hardy", 1938, "English", ["Mathematics"])
discrete_mathematics = Book("Discrete Mathematics and Its Applications", "Kenneth H. Rosen", 1988, "English", ["Mathematics"])
probability_theory = Book("Probability Theory: The Logic of Science", "E.T. Jaynes", 2003, "English", ["Mathematics"])
statistical_learning = Book("The Elements of Statistical Learning", "Trevor Hastie", 2001, "English", ["Mathematics"])

books = [
    principito, alquimista, angel_demonio, probability_essentials, harry_potter, to_kill_a_mockingbird, lord_rings, hunger_games, catcher, gatsby, flies, catch, grapes, gone, lolita, slaughterhouse, watchmen, atonement, possession, sun, ragtime, naked_lunch, gravity_rainbow,
    white_noise, beloved, midnight_children, house_leaves, corrections, brief_wondrous, cloud_atlas, fortress, kavalier_clay, sympathizer, underground_railroad, lincoln_bardo, overstory,
    introduction_linear_algebra, calculus, abstract_algebra, real_analysis, complex_analysis, topology, number_theory, discrete_mathematics, probability_theory, statistical_learning
]